name: Purge jsDelivr Cache
on:
  release:
    types: [published]

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/mohamedellithy/${{ github.repository }}@latest/salla/widget.js"
